name: Testing

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-24.04
    steps:
      - name: Set Ignition Version
        run: |
          echo "GZ_VERSION=harmonic" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: ros-tooling/setup-ros@0.7.8
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@0.3.14
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
          import-token: ${{ secrets.REPO_TOKEN }}
